<?php
    echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer_links_categories')
        ->toHtml();

    ?>

<?php
    echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer_links_why_bl')
        ->toHtml();

    ?>

<?php
    echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer_links_policies')
        ->toHtml();

    ?>




